---
- name: Ensure pip3 is installed
  yum:
    name: python3-pip
    state: present
    use_backend: dnf4
  become: yes

- name: Ensure required Python packages are installed
  pip:
    name:
      - requests
      - openpyxl
    state: present
    executable: pip3
  become: yes

- name: Fetch Dell laptops from Amazon
  uri:
    url: "{{ amazon_url }}"
    return_content: yes
  register: webpage_content

- name: Parse the webpage content
  set_fact:
    laptops: "{{ webpage_content.content | regex_findall('Dell [^<]+') | map('regex_replace', 'Dell ', '') | map('regex_replace', '[^a-zA-Z0-9 ]', '') | unique }}"
    prices: "{{ webpage_content.content | regex_findall('\\$[0-9,]+\\.[0-9]{2}') }}"

- name: Combine laptop names and prices
  set_fact:
    laptop_details: "{{ laptops | zip(prices) | map('join', '|') | join(',') }}"

- name: Debug laptop details variable
  debug:
    var: laptop_details

- name: Create Excel file with laptop details
  command: >
    python3 roles/fetch_dell_laptops/files/create_excel.py "{{ laptop_details }}"
  delegate_to: localhost

- name: Send the Excel file via email
  command: >
    python3 roles/fetch_dell_laptops/files/send_email.py "{{ email }}" "/tmp/dell_laptops.xlsx"
  delegate_to: localhost