name: Ansible Automation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          inventory: inventory.ini
          key: ${{ secrets.ANSIBLE_PRIVATE_KEY }}

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.ini playbook.yml